#include "dma.h"
#include "stm32f103x6.h"

void vDMA_Init(void) {

	// CLOCK ENABLE FOR DMA 1 IN AHB BUS
	RCC->AHBENR |= RCC_AHBENR_DMA1EN;

	// DISABLE PERIPHERAL BEFORE CONFIGURATION
	DMA1_Channel4->CCR &= ~DMA_CCR_EN;

	// DATA TRANSFER DIRECTION - READ FROM MEMORY WRITE TO PERIPHERAL
	DMA1_Channel4->CCR |= DMA_CCR_DIR;

	// CIRCULAR MODE DISABLE
	DMA1_Channel4->CCR &= ~DMA_CCR_CIRC;

	// PERIPHERAL INCREMENT MODE DISABLED
	DMA1_Channel4->CCR &= ~DMA_CCR_PINC;

	// MEMORY INCREAMENT MODE ENABLED
	DMA1_Channel4->CCR |= DMA_CCR_MINC;

	// PERIPHERAL SIZE 8 BIT BY PSIZE = 00
	DMA1_Channel4->CCR &= ~DMA_CCR_PSIZE;

	// MEMORY SIZE 8 BIT BY MSIZE = 00
	DMA1_Channel4->CCR &= ~DMA_CCR_MSIZE;

	// PRIORITY LEVEL LOW BY PL = 00
	DMA1_Channel4->CCR &= ~DMA_CCR_PL;

	// MEMORY TO MEMORY MODE DISABLED
	DMA1_Channel4->CCR &= ~DMA_CCR_MEM2MEM;

}


void vDMA_USART_Transmit (uint8_t *buffer, uint16_t length) {

	// DISABLE PERIPHERAL BEFORE CONFIGURATION
	DMA1_Channel4->CCR &= ~DMA_CCR_EN;

	// PERIPHERAL ADDRESS
	DMA1_Channel4->CPAR = (uint32_t)&USART1->DR;

	// MEMORY ADDRESS
	DMA1_Channel4->CMAR = (uint32_t)buffer;

	// NUMBER OF BYTES
	DMA1_Channel4->CNDTR = length;

	// CLEAR TC FLAG
	DMA1->IFCR |= DMA_IFCR_CTCIF4;

	// ENABLE PERIPHERAL AFTER CONFIGURATION
	DMA1_Channel4->CCR |= DMA_CCR_EN;

}
